# Site settings
title: "Skymouse Studios"
description: "A digital ad agency that helps you grow your business. No nonsense."
baseurl: #"https://skymousestudios.com"
url: "skymousestudios.com"
cover: "/library/cover.png"
logo: "/library/images/logos/skymse-logo-circle.png"
username: "@skymousestudios"
email: "sos@skymousestudios.com"
location: "Indianapolis, IN • Nashville, TN"
color: "#F99C1C"

# sass/css minify
sass:
  style: compressed

permalink: pretty

plugins:
  - jekyll-menus

collections:
  services:
    output: true
    permalink: /:collection/:name
  casestudies:
    output: true
    permalink: /work/:name
  pages:
    output: true
    permalink: /:name
  series:
    output: true
    permalink: /:name