# Site settings
title: "Skymouse Studios"
description: "A web design studio that helps you build a website you love. No nonsense."
baseurl: #"https://skymousestudios.com"
url: "skymousestudios.com"
cover: "/library/cover.png"
logo: "/library/images/logos/skymse-logo-circle.png"
username: "@skymousestudios"
email: "sos@skymousestudios.com"
location: "Indianapolis, IN • Nashville, TN"
color: "#F99C1C"

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# sass/css minify
sass:
  style: compressed

include: ["_pages"]
permalink: /:title/

collections:
  services:
    output: true
    permalink: /:collection/:name
  casestudies:
    output: true
    permalink: /our-work/:name

# Links to include in menu navigation
links:
  - title: Why Skymouse
    url: /why-skymouse
  - title: What you can do
    url: /what-you-can-do
  - title: Our Work
    url: /work
  - title: Pricing
    url: /pricing

# Footer Nav Links
footer:
  company:
    - title: About
      url: /about
    - title: Clients
      url: /clients
    - title: Careers
      url: /careers
    - title: Brand Guide
      url: /brand-guide
  services:
    - title: Why Skymouse
      url: /why-skymouse
    - title: What you can do
      url: /what-you-can-do
    - title: Process
      url: /process
    - title: Pricing
      url: /pricing
  resources:
    - title: Blog
      url: /blog
    - title: Book Reports
      url: /book-reports
    - title: Downloads
      url: /downloads
    - title: Podcast
      url: /podcast

# Links to Social Media
socials:
  - name: instagram
    url: "https://www.instagram.com/SkymouseStudios/"
  - name: linkedin
    url: "https://www.linkedin.com/company/skymouse-studios-and-entertainment"
  - name: twitter
    url: "https://twitter.com/SkymouseStudios"
  - name: facebook
    url: "https://www.facebook.com/Skymouse-Studios-1667422846889253"

# Descriptions for Blog Categories
series:
  - cat: New To Branding
    desc: "How to get started, from square one"
  - cat: Business Spotlight
    desc: "A look at businesses, and how they work"
  - cat: Tips and Tricks
    desc: "The best of the best for doing better work"
  - cat: Apps in the Workplace
    desc: "How to make the most of apps in your business"