# Site settings
title: "Skymouse Studios"
description: "Digital marketing that helps grow small businesses."
baseurl: "https://skymousestudios.com"
url: "skymousestudios.com"
cover: "/library/cover.png"
logo: "/library/images/logos/skymse-logo-circle.png"
username: "@skymousestudios"
email: "sos@skymousestudios.com"
location: "Indianapolis, IN • Chattanooga, TN"
color: "#F99C1C"

# sass/css minify
sass:
  style: compressed

plugins:
  - jekyll-menus
  - jekyll-redirect-from

collections:
  services:
    output: true
    permalink: /:collection/:name
  casestudies:
    output: true
    permalink: /work/:name
  pages:
    output: true
    permalink: /:name