# Site settings
title: "Skymouse Studios"
description: "A web design studio that helps you build a website you love. No nonsense."
baseurl: #"https://skymousestudios.com"
url: "skymousestudios.com"
cover: "/library/cover.png"
logo: "/library/images/.png"
username: "@skymousestudios"
email: "sos@skymousestudios.com"
location: "Indianapolis, IN • Nashville, TN"
color: "#F99C1C"

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# sass/css minify
sass:
  style: compressed

include: ["_pages"]
permalink: /:title/

collections:
  services:
    output: true
    permalink: /:collection/:name
  casestudies:
    output: true
    permalink: /:collection/:name

# Links to include in menu navigation
links:
  - title: Why Skymouse
    url: /why-skymouse.html
  - title: What you can do
    url: /what-you-can-do.html
  - title: Pricing
    url: /pricing.html
  - title: Resources
    url: /resources.html 
  - title: Contact
    url: /contact.html

# Links to Social Media
social:
  - name: instagram
    url: "https://www.instagram.com/SkymouseStudios/"
  - name: linkedIn
    url: "https://www.linkedin.com/company/skymouse-studios-and-entertainment"
  - name: youtube
    url: "https://www.youtube.com/channel/UCNaO9FKEx5GiagyapRpuehQ"
  - name: twitter
    url: "https://twitter.com/SkymouseStudios"
  - name: facebook
    url: "https://www.facebook.com/Skymouse-Studios-1667422846889253"

# Descriptions for Blog Categories
descriptions:
  - cat: Website
    desc: "Things that make life better."
  - cat: Brand
    desc: "Developing a better me"
  - cat: Hosting
    desc: "Developing a better me"
  - cat: SEO
    desc: "Developing a better me"

profiles:
  - name: John Welch
    title: Director of Business Development
    twitter: https://twitter.com/lifeofwelch
    handle: "@LifeOfWelch"
    desc: Musician, Loving Husband and Father. I'm also a singing Chef.
    img: /library/images/profile/johns-profile.jpg
  - name: Patrick Hanus
    title: Creative Director
    twitter: https://twitter.com/thehsedition
    handle: "@thHsEdition"
    desc: Staff Writer for the Patrick Hanus Show. Follow me for a great time.
    img: /library/images/profile/patricks-profile.jpg