# Site settings
title: "Skymouse Studios"
description: "A web design studio that helps you build a website you love. No nonsense."
baseurl: "https://skymousestudios.com"
url: "skymousestudios.com"
cover: "/library/cover.png"
logo: "/library/images/logos/skymse-logo-circle.png"
username: "@skymousestudios"
email: "sos@skymousestudios.com"
location: "Indianapolis, IN • Nashville, TN"
color: "#F99C1C"

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# sass/css minify
sass:
  style: compressed

include: ["_pages"]
permalink: /:path:output_ext

plugins:
  - jekyll-menus

collections:
  services:
    output: true
    permalink: /:collection/:name
  casestudies:
    output: true
    permalink: /work/:name

# Descriptions for Blog Categories
series:
  - cat: New To Branding
    desc: "How to get started, from square one."
  - cat: Business Spotlight
    desc: "A look at businesses, and how they work."
  - cat: Tips and Tricks
    desc: "The best of the best for doing better work."
  - cat: Apps in the Workplace
    desc: "How to make the most of apps in your business."