# Site settings
title: "Skymouse Studios - Transparent. Responsive. Webdesign"
description: "A web design studio that helps you build a website you love. No nonsense."
baseurl: #"https://skymousestudios.com"
url: "SkymouseStudios.com"
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# User settings
username: Patrick Hanus
user_title: Patrick Hanus | Creative Director
email: patrick@skymse.com
twitter_username: "@thehsedition"
github_username:  "@thehsedition"
gplus_username:  "@thehsedition"
disqus_username: "@thehsedition"

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# sass/css minify
sass:
  style: compressed

include: ["_pages"]
permalink: /:title/

collections:
  products:
    output: true
    permalink: /:collection/:name
  case_studies:
    output: true
    permalink: /:collection/:name

# Links to include in menu navigation
links:
  - title: About
    url: /about.html
  - title: Our Work
    url: /work.html
  - title: Pricing
    url: /pricing.html
  - title: Stories
    url: /stories.html 
  - title: Contact
    url: /contact.html

# Links to Social Media
social:
  - name: Instagram
    url: https://bit.ly/ph-insta
  - name: Vimeo
    url: https://bit.ly/ph-vimeo
  - name: LinkedIn
    url: https://bit.ly/ph-LinkedIn
  - name: YouTube
    url: https://bit.ly/ph-youtube
  - name: GitHub
    url: https://bit.ly/ph-github
  - name: Twitter
    url: https://bit.ly/ph-twitter

# Descriptions for Blog Categories
descriptions:
  - cat: Website
    desc: "Things that make life better."
  - cat: Brand
    desc: "Developing a better me"
  - cat: Hosting
    desc: "Developing a better me"
  - cat: SEO
    desc: "Developing a better me"
