---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: _casestudies
  label: Case studies
  create: documents
  match: "**/*"
- type: directory
  path: _services
  label: Services
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _profiles
  label: Profiles
  create: all
  match: "**/*"
- type: directory
  path: _data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml}"
upload_dir: uploads
public_path: "/library"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
