---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _case_studies
  label: Case studies
  create: all
  match: "**/*"
- type: directory
  path: _services
  label: Services
  create: all
  match: "**/*"
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
upload_dir: uploads
public_path: "/library"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
